incarnation: collektive

network-model:
  type: ConnectWithinDistance
  parameters: [2]

_pool: &program
  - time-distribution: 1
    type: Event
    actions:
      - type: RunCollektiveProgram
        parameters: [collektive.exercises.BasicExercisesKt.distanceToSource]

deployments:
  - type: GraphStreamDeployment
    parameters: [15, 2, 0, PreferentialAttachment]
    programs:
      - *program
    contents:
      - molecule: isSource
        concentration: true

monitors:
  type: SwingGUI
  parameters:
    graphics: basicExercises.json

launcher:
  parameters:
    autoStart: false