incarnation: collektive

network-model:
  type: ConnectWithinDistance
  parameters: [2]

_pool: &program
  - time-distribution: 1
    type: Event
    actions:
      - type: RunCollektiveProgram
        parameters: [collektive.exercises.AdvancedExercisesKt.distanceFurthestNodeToSource]

deployments:
  - type: GraphStreamDeployment
    parameters: [15, 2, 0, PreferentialAttachment]
    programs:
      - *program
    contents:
      - molecule: isSource
        concentration: true
      - molecule: isFurthest
        concentration: false
      - molecule: sources
        concentration: [0, 14]

monitors:
  type: SwingGUI
  parameters:
    graphics: advancedExercises.json

launcher:
  parameters:
    autoStart: false