[versions]
alchemist = "42.2.8"
kotlin = "2.1.21"
collektive = "26.0.0"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-euclidean-geometry = { module = "it.unibo.alchemist:alchemist-euclidean-geometry", version.ref = "alchemist" }
alchemist-incarnation-collektive = { module = "it.unibo.collektive:alchemist-incarnation-collektive", version.ref = "collektive" }
collektive-dsl = { module = "it.unibo.collektive:collektive-dsl", version.ref = "collektive" }
collektive-stdlib = { module = "it.unibo.collektive:collektive-stdlib", version.ref = "collektive" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[bundles]
alchemist = ["alchemist", "alchemist-euclidean-geometry", "alchemist-incarnation-collektive", "alchemist-swingui"]
collektive = [ "collektive-stdlib", "collektive-dsl" ]

[plugins]
collektive = { id = "it.unibo.collektive.collektive-plugin", version.ref = "collektive" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
